# Generated by Django 5.2.14 on 2026-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='address',
            field=models.CharField(default='jaipur', max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
