# Generated by Django 5.2.14 on 2026-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subject_address_subject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='address_1',
            field=models.CharField(default='jaipur', max_length=255),
        ),
    ]
