# Generated by Django 5.2.14 on 2026-05-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subject_address_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='city',
            field=models.CharField(default='mp', max_length=100),
        ),
    ]
